# Generated by Django 2.1.2 on 2018-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181127_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(related_query_name='tags', to='questions.Question'),
        ),
    ]
